### ISSUE TITLE
Memory usage is growing

### ISSUE THREAD

**Issue by stucki** [baschny/typo3-merged#54]
Just FYI, since a few weeks the script needs more than 256M memory. I have raised it to 512M but I am not sure how long this will suffice.

How can we minimize the memory usage again?

**Comment by sgrossberndt** [comment]
I guess by removing any reference to 4.5 since this is not needed to check anymore as 4.5 is ELTS.

**Comment by sgrossberndt** [comment]
I guess this is fine again and this issue can be closed?

**Comment by stucki** [comment]
Just tried. It works now with the default value (128M). Thanks!

This issue can be closed.
